services:

  windows:
    image: dockurr/windows
    networks: [ci-net]
    cap_add: [NET_ADMIN]
    environment:
      VERSION: "11"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      USER_PORTS: "22"
      DISK_CACHE: "writeback"
      DISK_IO: "threads"
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - ./windows/oem:/oem:ro
      - windows-data:/storage
    restart: unless-stopped

  adaptixc2:
    image: ghcr.io/tgjls/adaptixc2:1.2
    networks:
      ci-net:
        ipv4_address: 172.28.0.10
    restart: unless-stopped

  testing-kit:
    image: ghcr.io/tgjls/testing-kit:2.1.0
    networks: [ci-net]
    ports:
      - "1234:1234"
    environment:
      TESTING_KIT_DB: /data/testing_kit.db
      TASKS_SEED_PATH: /app/default_tasks.yaml
    volumes:
      - ./config/config.yaml:/app/config.yaml:ro
      - ./config/tasks.yaml:/app/default_tasks.yaml:ro
      - ./ssh/id_test:/run/secrets/ssh_key:ro
      - testing-kit-db:/data
    restart: unless-stopped

networks:
  ci-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  windows-data:
  testing-kit-db:
