server:
  url: https://adaptixc2:4321
  endpoint: /endpoint

operator:
  name: ci
  password: pass

setup:
  project: ci
  agent_output: /tmp/ci_agent.exe
  listener:
    name: ci_http
    type: BeaconHTTP
    config:
      host_bind: "0.0.0.0"
      port_bind: 8080
      callback_addresses:
        - "172.28.0.10:8080"
      http_method: POST
      uri:
        - /beacon
      user_agent:
        - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
      hb_header: "X-Beacon-Id"
      encrypt_key: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"
      ssl: false
      page-payload: '{"status":"ok","data":"<<<PAYLOAD_DATA>>>","metrics":"sync"}'
  agent:
    agent: beacon
    listener: ci_http
    listener_type: BeaconHTTP
    config:
      arch: x64
      format: Exe
      sleep: "0s"
      jitter: 0

ssh:
  host: windows
  port: 22
  username: ci_runner
  key_path: /run/secrets/ssh_key
  source_path: /tmp/ci_agent.exe
  agent_path: '/ci/agent.exe'
  terminate: true
  connect_retries: 90
  connect_retry_interval: 20
